on:
  fork:
  push:
    branches: [master]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "<h3>Hello, @${{ github.actor }},  thank you for opening an issue.</h3>"
          pr-message: "<h3>Hello, @${{ github.actor }},  thank you for opening a pull request.</h3>"
          footer: "Soon the maintainers/owner will review it and provide you with feedback/suggestions.<br>If you think it's something urgent, feel free to reach out to <a href='https://twitter.com/vishal_21121'>Vishal</a> on <b>Twitter</b>.<br><br><br><b>Give us a ⭐ to show some support</b><br><b>Happy OpenSource 🚀</b>"
